services:
  proyecto1php:
    build:
      context: ./.docker
      dockerfile: Dockerfile
      args:
        - USERNAME=${USUARIO:-app}
        - USER_UID=${USUARIO_UID:-1000}
        - USER_GID=${USUARIO_GID:-1000}
    container_name: containerphp

    user: ${USUARIO:-app}:${USUARIO_GID:-1000}

    #Crear un volumen para almacenar mi página web
    volumes:
      - ./src:/var/www/html
      - .docker/apache/apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - .docker/xdebug/debug.ini:/usr/local/etc/php/conf.d/debug.ini

    ports:
      - 8080:80
    expose:
      - 80
    networks:
      - proyecto1
    links:
      - mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"


  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3310:3306
    networks:
      - proyecto1
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: proyecto1
      MARIADB_USER: miguela
      MARIADB_PASSWORD: aleugim
    command:
      --default-authentication-plugin=mysql_native_password

  mongo:
    image: mongo:7.0-jammy
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - proyecto1
    ports:
      - 27018:27017

networks:
  proyecto1:
    name: proyecto1
    driver: bridge

volumes:
  mariadb_data: